# English (fallback) UI strings for the wlr-utils tools.
# The command line (clap) is English-only and not localised. This catalog is also the
# source for the no-`i18n`-feature English fallback generated by build.rs.

tab-all = All
tab-windows = Windows
tab-outputs = Screens

filter-hint = Filter…
screen-label = Screen { $name }
loading = …
show-system = System windows

error = wlr-chooser: { $error }
pip-gone = Source window closed

# Shared frozen overlay (region selector / colour picker)
overlay-region-hint = Drag to select · Esc to cancel
overlay-pick-hint = Click to pick · Esc to cancel
overlay-magnify-hint = Scroll to zoom · Esc to quit
