# English (fallback) UI strings for the wlr-utils tools.
# The command line (clap) is English-only and not localised. This catalog is also the
# source for the no-`i18n`-feature English fallback generated by build.rs.

tab-all = All
tab-windows = Windows
tab-outputs = Screens

filter-hint = Filter…
screen-label = Screen { $name }
loading = …
show-system = System windows

error = wlr-chooser: { $error }
pip-gone = Source window closed

# Shared frozen overlay (region selector / colour picker)
overlay-region-hint = Drag to select · Esc to cancel
overlay-pick-hint = Click to pick · Esc to cancel
overlay-magnify-hint = Scroll to zoom · Esc to quit

# Live annotation overlay (wlr-draw)
draw-hint = Draw · h for help · Esc to leave
draw-passthrough-hint = Click-through — Caps Lock to draw again
draw-text-hint = Type · Enter to place · Esc to cancel
draw-spotlight-hint = Spotlight · drag a shape, or move the cursor · wheel/i k size · tilt/j l dim · Shift off to end
draw-tool-pen = Pen
draw-tool-rect = Rectangle
draw-tool-mask = Mask (filled box)
draw-tool-arrow = Arrow
draw-tool-text = Text
draw-tool-eraser = Eraser
draw-tool-move = Move
draw-palette-title = Colour
draw-help-title = wlr-draw — keys
draw-help-tools = tools (pen, line, rect, ellipse, arrow, text, eraser)
draw-help-color = colour palette
draw-help-undo = undo / redo
draw-help-width = stroke width
draw-help-clear = clear all
draw-help-visibility = hide / show
draw-help-help = this help
draw-help-leave = leave draw mode
draw-help-constrain = hold: constrain (circle / square / axis)
draw-help-spotlight = hold: spotlight (dim around shape / cursor)
draw-help-spotlight-tune = spotlight: wheel/i,k size · tilt/j,l dim
draw-help-passthrough = Caps Lock: click through to apps
draw-help-draw = left-drag: draw
draw-help-snap = pen, hold still: snap to a clean shape
draw-help-text = text: click, type, Enter
draw-help-move = arrows: nudge selection · Shift 1px · Ctrl big step
draw-help-freeze = Space: freeze the screen to annotate a still
draw-help-rightmove = right-drag: move any element
tray-status-drawing = Drawing
tray-status-idle = Idle (click-through)
tray-toggle = Toggle draw mode
tray-clear = Clear
tray-undo = Undo
tray-shortcuts = Shortcuts
tray-quit = Quit
